version: '3.8'

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
